name: mne
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1=h57928b3_1
  - aiohappyeyeballs=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.10.5=py39ha55e580_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - antropy=0.1.9=pyhd8ed1ab_0
  - anyio=4.4.0=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha55e580_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - autoreject=0.4.3=pyhd8ed1ab_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=2.123=mkl
  - blas-devel=3.9.0=23_win64_mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.6=h85f69ea_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py39ha51f57c_2
  - brotlicffi=1.1.0.0=py39h99910a6_1
  - bzip2=1.0.8=h2466b09_7
  - c-blosc2=2.15.1=hb461149_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h91e5215_2
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.0=py39ha55e580_1
  - cftime=1.6.4=py39h4b0a98a_1
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cmasher=1.8.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py39h2b77a98_0
  - cpuonly=2.0=0
  - cuda-cccl=12.6.37=0
  - cuda-cccl_win-64=12.6.37=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-libraries-dev=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.68=0
  - cuda-opencl-dev=12.6.68=0
  - cuda-profiler-api=12.6.68=0
  - cuda-runtime=12.4.0=0
  - cuda-version=12.6=3
  - cudnn=9.3.0.75=hffc9a7f_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - darkdetect=0.8.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.5=py39ha51f57c_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - deepdiff=8.0.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - dipy=1.9.0=py39h41a24ab_0
  - double-conversion=3.3.0=h63175ca_0
  - edfio=0.4.3=pyhd8ed1ab_0
  - eeglabio=0.0.2.post4=pyhd8ed1ab_0
  - eigen=3.4.0=h91493d7_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.5.0=h63175ca_1
  - ffmpeg=6.1.2=gpl_h9673905_705
  - ffmpeg-python=0.2.0=pyhff2d567_1
  - filelock=3.15.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py39ha55e580_0
  - fooof=1.1.1=pyhecae5ae_1
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hdaf720e_2
  - frozenlist=1.4.1=py39ha55e580_1
  - future=1.0.0=pyhd8ed1ab_2
  - giflib=5.2.2=h64bf75a_0
  - gl2ps=1.4.2=had7236b_1
  - glew=2.1.0=h39d44d4_2
  - glib=2.80.3=h7025463_2
  - glib-tools=2.80.3=h4394cf3_2
  - graphite2=1.3.13=h63175ca_1003
  - gst-plugins-base=1.24.6=hb0a98b8_0
  - gstreamer=1.24.6=h5006eae_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5io=0.2.4=pyhecae5ae_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py39h0b25466_100
  - harfbuzz=9.0.0=h81778c3_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.3=nompi_h2b43c12_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh7428d3b_8
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h63175ca_0
  - idna=3.8=pyhd8ed1ab_0
  - imagecodecs=2024.6.1=py39hd99415c_3
  - imageio=2.35.1=pyh12aca89_0
  - imageio-ffmpeg=0.5.1=pyhd8ed1ab_0
  - imbalanced-learn=0.12.4=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib-resources=6.4.4=pyhd8ed1ab_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - importlib_resources=6.4.4=pyhd8ed1ab_0
  - inflate64=1.0.0=py39ha55989b_1
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.18.1=pyh7428d3b_3
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsoncpp=1.9.5=h2d74725_1
  - jsonpointer=3.0.0=py39hcbf5309_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hcbf5309_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - jxrlib=1.1=hcfcfb64_3
  - kiwisolver=1.4.5=py39h2b77a98_2
  - krb5=1.21.3=hdf4eb48_0
  - lazy-loader=0.4=pyhd8ed1ab_1
  - lazy_loader=0.4=pyhd8ed1ab_1
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libaec=1.1.3=h63175ca_0
  - libavif16=1.1.1=h4e96d62_1
  - libblas=3.9.0=23_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=23_win64_mkl
  - libclang13=18.1.8=default_ha5278ca_3
  - libcublas=12.4.2.65=0
  - libcublas-dev=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufft-dev=11.2.0.44=0
  - libcurand=10.3.7.68=0
  - libcurand-dev=10.3.7.68=0
  - libcurl=8.9.1=h18fefc2_0
  - libcusolver=11.6.0.99=0
  - libcusolver-dev=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libcusparse-dev=12.3.0.142=0
  - libdeflate=1.21=h2466b09_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libflang=5.0.0=h6538335_20180525
  - libglib=2.80.3=h7025463_2
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=23_win64_mkl
  - liblapacke=3.9.0=23_win64_mkl
  - libmatio=1.5.27=h0a2718b_0
  - libnetcdf=4.9.2=nompi_h92078aa_114
  - libnpp=12.2.5.2=0
  - libnpp-dev=12.2.5.2=0
  - libnvfatbin=12.6.68=0
  - libnvfatbin-dev=12.6.68=0
  - libnvjitlink=12.4.99=0
  - libnvjitlink-dev=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libnvjpeg-dev=12.3.1.89=0
  - libogg=1.3.5=h2466b09_0
  - libopenblas=0.3.28=pthreads_hf0a32cb_0
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.43=h19919ed_0
  - libprotobuf=5.28.3=h8309712_1
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.46.0=h2466b09_0
  - libssh2=1.11.0=h7dfc565_0
  - libtheora=1.1.1=hc70643c_1006
  - libtiff=4.6.0=hb151862_4
  - libuv=1.48.0=hcfcfb64_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.12.7=h0f24e4e_4
  - libxslt=1.1.39=h3df6e99_0
  - libzip=1.10.1=h1d365fa_3
  - libzlib=1.3.1=h2466b09_1
  - libzopfli=1.0.3=h0e60522_0
  - littleutils=0.2.4=pyhd8ed1ab_1
  - llvm-meta=5.0.0=0
  - llvmlite=0.43.0=py39he94c479_1
  - loguru=0.7.2=py39hcbf5309_2
  - lxml=5.3.0=py39hcc8b0fb_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=2.1.5=py39ha55e580_1
  - matplotlib-base=3.8.4=py39he1095e7_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - meshio=5.3.5=pyhd8ed1ab_0
  - mffpy=0.9.0=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2024.1.0=h66d3029_694
  - mkl-devel=2024.1.0=h57928b3_694
  - mkl-include=2024.1.0=h66d3029_694
  - mne=1.7.0=hd8ed1ab_3
  - mne-base=1.7.0=pyha770c72_3
  - mne-connectivity=0.7.0=pyhd8ed1ab_2
  - mne-icalabel=0.7.0=pyhd8ed1ab_0
  - mne-qt-browser=0.6.3=pyha770c72_0
  - more-itertools=10.4.0=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py39h2b77a98_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.5=py39ha55e580_1
  - multivolumefile=0.2.3=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf4=1.7.2=nompi_py39h9ffc7cd_101
  - networkx=3.2.1=pyhd8ed1ab_0
  - neurodsp=2.3.0=pyhd8ed1ab_0
  - nibabel=5.3.2=pyha770c72_1
  - nilearn=0.10.4=pyhd8ed1ab_0
  - nlohmann_json=3.11.3=he0c23c2_1
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.60.0=py39h5dcb127_0
  - numexpr=2.7.3=py39h2e25243_2
  - numpy=1.23.0=py39h1a62c8c_0
  - onnx=1.17.0=py39h55c0331_2
  - onnxruntime=1.19.2=py39hcbb09d5_200_cuda
  - openh264=2.4.1=h63175ca_0
  - openjpeg=2.5.2=h3d672ee_0
  - openmeeg=2.5.12=py39h13202ca_1
  - openmp=5.0.0=vc14_1
  - openpyxl=3.1.5=py39ha55989b_1
  - openssl=3.5.0=ha4e3fda_1
  - orderly-set=5.2.2=pyhd8ed1ab_0
  - outdated=0.2.2=pyhd8ed1ab_2
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=1.5.3=py39h2ba5b7c_1
  - pandas-flavor=0.7.0=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py39hfa8c767_0
  - pingouin=0.5.5=pyhd8ed1ab_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.4=h63175ca_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - proj=9.3.1=he13c7e8_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - prompt_toolkit=3.0.47=hd8ed1ab_0
  - protobuf=5.28.3=py39ha51f57c_0
  - psutil=6.0.0=py39ha55e580_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pugixml=1.14=h63175ca_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - py7zr=0.21.0=pyhd8ed1ab_0
  - pyaml=24.9.0=pyhd8ed1ab_0
  - pybcj=1.0.2=py39ha55989b_0
  - pybv=0.7.5=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pycryptodomex=3.20.0=py39ha55e580_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pymatreader=1.0.0=pyhd8ed1ab_0
  - pyopengl=3.1.6=pyhd8ed1ab_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyppmd=1.1.0=py39h99910a6_0
  - pyqt=5.15.9=py39hb77abff_5
  - pyqt5-sip=12.12.2=py39h99910a6_5
  - pyqtgraph=0.13.7=pyhd8ed1ab_0
  - pyreadline3=3.5.4=py39h1941036_0
  - pyserial=3.5=pyhd8ed1ab_1
  - pysocks=1.7.1=pyh0701188_6
  - pytables=3.9.2=py39h2499b97_3
  - pytest=8.3.3=pyhd8ed1ab_0
  - python=3.9.19=h4de0772_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyhe33e51e_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-picard=0.7=pyh8a188c0_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pytorch=2.2.2=py3.9_cpu_0
  - pytorch-cuda=12.4=h3fd98bf_6
  - pytorch-mutex=1.0=cpu
  - pytz=2024.1=pyhd8ed1ab_0
  - pyvista=0.44.1=pyhd8ed1ab_0
  - pyvistaqt=0.11.1=pyhd8ed1ab_0
  - pywavelets=1.6.0=py39h4b0a98a_0
  - pywin32=306=py39h99910a6_2
  - pywinpty=2.0.13=py39ha51f57c_1
  - pyyaml=6.0.2=py39ha55e580_0
  - pyzmq=26.2.0=py39h03e5c00_0
  - pyzstd=0.16.1=py39h9bf74da_0
  - qdarkstyle=3.2.3=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.8=h06adc49_23
  - qtpy=2.4.1=pyhd8ed1ab_0
  - rav1e=0.6.6=h975169c_2
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.20.0=py39h92a245a_1
  - scikit-image=0.24.0=py39h2366fc2_2
  - scikit-learn=1.3.0=py39hfa9d973_0
  - scikit-optimize=0.10.2=pyhd8ed1ab_0
  - scipy=1.13.0=py39h1a10956_1
  - scooby=0.10.0=pyhd8ed1ab_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_0
  - setuptools=72.2.0=pyhd8ed1ab_0
  - setuptools-scm=8.1.0=pyhd8ed1ab_0
  - sip=6.7.12=py39h99910a6_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h23299a8_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.46.0=h2466b09_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.2=py39h4b0a98a_0
  - svt-av1=2.2.1=he0c23c2_0
  - sympy=1.13.2=pyh04b8f61_3
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2021.12.0=hc790b64_4
  - tbb-devel=2021.12.0=h053bfa6_4
  - terminado=0.18.1=pyh5737063_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2024.6.18=pyhd8ed1ab_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.2.2=py39_cpu
  - torchvision=0.17.2=py39_cpu
  - tornado=6.4.1=py39ha55e580_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trame=3.6.3=pyhd8ed1ab_0
  - trame-client=3.2.5=pyhd8ed1ab_0
  - trame-server=3.1.2=pyhd8ed1ab_0
  - trame-vtk=2.8.10=pyhd8ed1ab_0
  - trame-vuetify=2.7.1=pyhd8ed1ab_0
  - trimesh=4.6.13=pyh7b2049a_0
  - trx-python=0.3=py39hcbf5309_0
  - types-python-dateutil=2.9.0.20240821=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h8827d51_1
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.1.0=py39ha55989b_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - utfcpp=4.0.5=h57928b3_0
  - vc=14.3=h8a93ad2_20
  - vc14_runtime=14.40.33810=hcc2c482_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - vtk=9.2.6=qt_py39h1234567_223
  - vtk-base=9.2.6=qt_py39h1234567_223
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - win32_setctime=1.1.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - wrapt=1.16.0=py39ha55e580_1
  - wslink=2.1.2=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xarray=2024.3.0=pyhd8ed1ab_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.9.8=py39ha55e580_0
  - zeromq=4.3.5=he1f189c_4
  - zfp=1.0.1=he0c23c2_1
  - zipfile-deflate64=0.2.0=py39ha55989b_4
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_1
  - zlib-ng=2.2.1=he0c23c2_0
  - zstandard=0.23.0=py39h9bf74da_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - cmcrameri==1.9
      - cmocean==4.0.3
      - colorcet==3.1.0
      - cython==3.1.2
      - intel-cmplr-lib-ur==2024.2.1
      - intel-openmp==2024.2.1
      - joblib==1.4.0
      - mat73==0.65
      - matplotlib==3.8.0
      - nolds==0.6.1
      - nolitsa==0.1
      - palettable==3.3.3
      - pooch==1.8.0
      - prettytable==3.11.0
      - pyecharts==2.0.6
      - pymrmr==0.1.11
      - pypalettes==0.1.3
      - pyriemann==0.6
      - scicomap==1.0.0
      - simplejson==3.19.3
      - ssvepanalysistoolbox==0.0.5
      - tqdm==4.66.0
      - vapeplot==0.0.8
prefix: E:\Anaconda\install\envs\mne
